### ISSUE TITLE
pyconfig.h: No such file or directory

### ISSUE THREAD

**Issue by callnothing** [thieman/dagobah#143]
Thank you very much and when I use pip to install dagobah in ubuntu 14.04(64),an error has happend,this is the log
------------------------------------------------------------------------

building 'lxml.etree' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/src

creating build/temp.linux-x86_64-2.7/src/lxml

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/home/chengchaowang/workspaces/project001/env001/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

src/lxml/lxml.etree.c:8:22: fatal error: pyconfig.h: No such file or directory

 #include "pyconfig.h"

                      ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
-------------------------------------------------------------------------------------

**Comment by rclough** [comment]
How are you building dagobah? This seems like a compilation error for one of dagobah's dependencies, not an issue with dagobah its self. I'm happy to help you figure out what it is though.

Some cursory googling tells me you might need to install the `python-dev` package from ubuntu: http://stackoverflow.com/questions/24829558/mpi4py-on-ubuntu-pyconfig-h-not-found

**Comment by callnothing** [comment]
thank you very much,finally i solved this problem and installed dagobah according to what you said,
but when i runing dagobahd,an error has happend,here is the log
------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/dagobahd", line 9, in <module>
    load_entry_point('dagobah==0.3.1', 'console_scripts', 'dagobahd')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/app.py", line 1, in <module>
    from .daemon import app, login_manager
  File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/daemon.py", line 249, in <module>
    dagobah = init_dagobah()
  File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/daemon.py", line 113, in init_dagobah
    backend = get_backend(config)
  File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/daemon.py", line 218, in get_backend
    return SQLiteBackend(**backend_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dagobah/backend/sqlite.py", line 38, in __init__
    super(SQLiteBackend, self).__init__()
  File "/usr/local/lib/python2.7/dist-packages/dagobah/backend/base.py", line 26, in __init__
    self.verify_required_packages()
  File "/usr/local/lib/python2.7/dist-packages/dagobah/backend/base.py", line 51, in verify_required_packages
    if Version(installed_version, partial=True) < Version(spec['version'], partial=True):
  File "/usr/local/lib/python2.7/dist-packages/semantic_version/base.py", line 75, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
  File "/usr/local/lib/python2.7/dist-packages/semantic_version/base.py", line 181, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '0.7.5.post2'

**Comment by thieman** [comment]
@callnothing Whoever's running Alembic just decided to go off the rails and start putting random strings in the versions, which is breaking our semantic version parsing. Please try installing Alembic 0.7.4 as a workaround. I'll create a separate issue to account for this.

```
pip install alembic==0.7.4
```

**Comment by thieman** [comment]
@callnothing please let us know if the workaround did not resolve your issue. For now I am going to close this issue as we've created a separate issue for the bug fix.
