### ISSUE TITLE
Unable to start dagobahd after successfully installed dagobah-0.3.1

### ISSUE THREAD

**Issue by zhenlongbai** [thieman/dagobah#145]
first,I am sorry for my poor English .

when i used dagobahd command .I get the follow error

/usr/local/lib/python2.7/site-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
Traceback (most recent call last):
  File "/usr/local/bin/dagobahd", line 9, in <module>
    load_entry_point('dagobah==0.3.1', 'console_scripts', 'dagobahd')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/dagobah/daemon/app.py", line 1, in <module>
    from .daemon import app, login_manager
  File "/usr/local/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 13, in <module>
    from ..email import get_email_handler
  File "/usr/local/lib/python2.7/site-packages/dagobah/email/__init__.py", line 4, in <module>
    from .basic import BasicEmail
  File "/usr/local/lib/python2.7/site-packages/dagobah/email/basic.py", line 7, in <module>
    import premailer
  File "/usr/local/lib/python2.7/site-packages/premailer/__init__.py", line 1, in <module>
    from premailer import Premailer, transform, __version__
  File "/usr/local/lib/python2.7/site-packages/premailer/premailer.py", line 2, in <module>
    from lxml import etree
ImportError: /usr/local/lib/python2.7/site-packages/lxml/etree.so: undefined symbol: exsltMathXpathCtxtRegister

**Comment by thieman** [comment]
This seems like something is wrong with your `lxml` version. I did a quick search and came up with this, maybe it will help?

http://stackoverflow.com/questions/6417881/still-cannot-properly-install-lxml-2-3-for-python-but-at-least-2-2-8-works

As this is not directly related to Dagobah but rather one of its dependencies, I'll close this issue.

**Comment by zhenlongbai** [comment]
thanks for you Answer.
