### ISSUE TITLE
InvalidRequestError: Session is already flushing

### ISSUE THREAD

**Issue by zhenlongbai** [thieman/dagobah#146]
Starting app on 0.0.0.0:9876
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/components.py", line 114, in run
    job.start()
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/core.py", line 407, in start
    self._commit_run_log()
  File "/usr/local/lib/python2.7/site-packages/dagobah/core/core.py", line 624, in _commit_run_log
    self.backend.commit_log(self.run_log)
  File "/usr/local/lib/python2.7/site-packages/dagobah/backend/sqlite.py", line 185, in commit_log
    self.session.flush()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1979, in flush
    raise sa_exc.InvalidRequestError("Session is already flushing")
InvalidRequestError: Session is already flushing

**Comment by thieman** [comment]
Some clarifying questions:

Is this happening every time you run Dagobah?
Is this happening right after startup or once you do something in particular?
Please run a `pip freeze` (in the Dagobah virtualenv if you are using one) and provide the output here so we can see which package versions you're running.
Please also provide any relevant logs surrounding the problem if you can.

**Comment by zhenlongbai** [comment]
I'm glad you reply in time and thanks .

It is not happen every time . when i modify the tasks , it maybe  throw exceptions .If it throw exception , I can't do anything. For example, I can't modify and delete tasks and jobs. I must restart Dagobah. I use Chrome browser with utf-8 .today ,I will run Dagobah and record my logs. At last ,I want to know , Dagobah can be used by multi-user at the same time
 
this is my package versions

pip freeze
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
alembic==0.7.4
backports.ssl-match-hostname==3.4.0.2
certifi==14.5.14
croniter==0.3.3
cssselect==0.9.1
dagobah==0.3.1
Flask==0.9
Flask-Login==0.2.6
Jinja2==2.7.3
lxml==3.4.2
Mako==1.0.1
MarkupSafe==0.23
MySQL-python==1.2.4b4
paramiko==1.11.0
premailer==1.13
pycrypto==2.6.1
pymongo==3.0
pysqlite==2.6.3
python-dateutil==2.1
PyYAML==3.10
requests==2.5.1
semantic-version==2.3.0
simplejson==3.6.5
six==1.9.0
SQLAlchemy==0.9.9
tornado==4.1
Werkzeug==0.10.4
zope.interface==4.1.2
