### ISSUE TITLE
Fresh dagobah install failing

### ISSUE THREAD

**Issue by utkarsh2012** [thieman/dagobah#159]
Just tried this on ubuntu and then on mac.

    (dagobah)➜  ~  dagobahd
    Creating new config file in home directory
    Traceback (most recent call last):
      File "/Users/usengar/.virtualenvs/dagobah/bin/dagobahd", line 7, in <module>
        from dagobah.daemon.app import daemon_entrypoint
      File "/Users/usengar/.virtualenvs/dagobah/lib/python2.7/site-packages/dagobah/daemon/app.py", line 1, in <module>
        from .daemon import app, login_manager
      File "/Users/usengar/.virtualenvs/dagobah/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 248, in <module>
        config = get_config_file()
      File "/Users/usengar/.virtualenvs/dagobah/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 70, in get_config_file
        new_config.write(return_standard_conf())
      File "/Users/usengar/.virtualenvs/dagobah/lib/python2.7/site-packages/dagobah/__init__.py", line 14, in return_standard_conf
        config_file = open(os.path.join(config_file_default_location, 'dagobahd.yml'))
    IOError: [Errno 2] No such file or directory: '/Users/usengar/dagobah/daemon/dagobahd.yml'

Any suggestions?

**Comment by rclough** [comment]
What does your /dagobah/daemon folder look like? Does the `dagobahd.yml` file actually exist there? It exists in this public repo pretty much where the install would expect it: https://github.com/thieman/dagobah/blob/master/dagobah/daemon/dagobahd.yml

I unfortunately am not the greatest with virtualenvs, could me some setuptools issue we have with virtualenvs? @thieman ?

**Comment by rclough** [comment]
Oh I think I see what's going on. It assumes the base config is in `/Users/usengar/dagobah/daemon/dagobahd.yml` which doesnt account for the fact that the base config is actually in a virtualenv folder.


Temporary fix would be to just save this file: https://raw.githubusercontent.com/thieman/dagobah/master/dagobah/daemon/dagobahd.yml and place it at `/Users/usengar/dagobah/daemon/dagobahd.yml`. We'll need to investigate how to get dagobah to recognize where the config is when installed with a virtualenv.

**Comment by utkarsh2012** [comment]
Dagobah created a config file here: `~/.dagobahd.yml` and it should use that file.
I don't really have `/Users/usengar/dagobah/daemon`.

When I manually create `/Users/usengar/dagobah/daemon/dagobahd.yml` I get this error on ubuntu, it works on mac.

    ubuntu@ip-10-70-6-19:~$ dagobahd
    Defaulting missing config key Logging.enabled to False
    WARNING:root:Defaulting missing config key Logging.enabled to False
    WARNING:root:Package pysqlite has version 2.6.3 which is later than specified version 2.6.0. If you experience issues, try downgrading to version 2.6.0.
    WARNING:root:Package sqlalchemy has version 1.0.6 which is later than specified version 0.9.4. If you experience issues, try downgrading to version 0.9.4.
    WARNING:root:Package alembic has version 0.7.6 which is later than specified version 0.6.4. If you experience issues, try downgrading to version 0.6.4.
    Traceback (most recent call last):
      File "/usr/local/bin/dagobahd", line 9, in <module>
        load_entry_point('dagobah==0.3.1', 'console_scripts', 'dagobahd')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/app.py", line 1, in <module>
        from .daemon import app, login_manager
      File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/daemon.py", line 249, in <module>
        dagobah = init_dagobah()
      File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/daemon.py", line 113, in init_dagobah
        backend = get_backend(config)
      File "/usr/local/lib/python2.7/dist-packages/dagobah/daemon/daemon.py", line 218, in get_backend
        return SQLiteBackend(**backend_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/dagobah/backend/sqlite.py", line 58, in __init__
        Base.metadata.create_all(self.engine)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3634, in create_all
        tables=tables)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1851, in _run_visitor
        with self._optional_conn_ctx_manager(connection) as conn:
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1844, in _optional_conn_ctx_manager
        with self.contextual_connect() as conn:
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2035, in contextual_connect
        self._wrap_pool_connect(self.pool.connect, None),
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
        e, dialect, self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
        exc_info
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2070, in _wrap_pool_connect
        return fn()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
        return _ConnectionFairy._checkout(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 708, in _checkout
        fairy = _ConnectionRecord.checkout(pool)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
        rec = pool._do_get()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1146, in _do_get
        return self._create_connection()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
        return _ConnectionRecord(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
        self.connection = self.__connect()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 602, in __connect
        connection = self.__pool._invoke_creator(self)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
        return dialect.connect(*cargs, **cparams)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
        return self.dbapi.connect(*cargs, **cparams)
    sqlalchemy.exc.OperationalError: (pysqlite2.dbapi2.OperationalError) unable to open database file

**Comment by rclough** [comment]
Gotcha. I suspect its gotta be some confusion with virtualenvs. I'll defer to @thieman  who knows much more about them than I.

**Comment by thieman** [comment]
Pretty sure this code is using `pkg_resources` which IIRC is supposed to be able to correctly find the actual install location of the library. https://github.com/thieman/dagobah/blob/master/dagobah/__init__.py

Whatever's going on, your virtualenv seems very unhappy, do you remember exactly how you installed the app? I'm also wondering what version of Python and pkg_resources are in that virtualenv. @rclough were you able to reproduce? I haven't had a chance to try yet.

**Comment by utkarsh2012** [comment]
I used `pip install dagobah` inside virtualenv to install on mac and `sudo pip install dagobah` to install on ubuntu (an ec2 instance just for dagobah, doing some testing). I should use virtualenv there?

**Comment by thieman** [comment]
Can you show us the traceback from Ubuntu?

**Comment by utkarsh2012** [comment]
It works on ubuntu too, I had to `sudo dagobahd`. So looks like the only issue is placement of `dagobahd.yml`

**Comment by thieman** [comment]
I'm confused, is it working or not on Ubuntu? If it's broken, I want to see what the traceback looks like outside of a virtualenv install.

**Comment by utkarsh2012** [comment]
Its working on Ubuntu and Mac both.

I got this stacktrace on ubuntu because I didn't run dagobah using sudo: https://github.com/thieman/dagobah/issues/159#issuecomment-116844207

These steps are needed to make dagobah work on ubuntu or mac:

1. `pip install dagobah` (if globally, use sudo)
2. Create: `/Users/usengar/dagobah/daemon/dagobahd.yml`
3. Run: `dagobahd` (if installed globally, use sudo)

**Comment by Littlegump** [comment]
uu~~I just want to know, whether THE dago can run on remote host properly without any adaption? 
Can I ask some questions about the dago who used on remote machines. I found a point that dago_center can not communication with dago_remote task, where the failure was trigger by the lib <paramiko>'s  edition. pip install dagobah(use paramiko 1.11.0), but i can't be functional property on remote. Only when i update the paramiko to edition 1.16.0 && fix the setup.py (install_requires's paramiko==1.16.0), then remote task can be executed. Sorry about my ugly English.

**Comment by Littlegump** [comment]
Hi, thieman, are you alive? haha~~

**Comment by Littlegump** [comment]
I 'm your fans just because of your license~
