### ISSUE TITLE
Dagobah failing after upgrade to 0.3.1 on OSX 10.9.5

### ISSUE THREAD

**Issue by extrinsicmedia** [thieman/dagobah#163]
Giving this error output:
```Logging output to /opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/dagobah.log
Logger initialized at level INFO
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.
Defaulting missing config key Dagobahd.ssh_config to ~/.ssh/config
WARNI [root] Defaulting missing config key Dagobahd.ssh_config to ~/.ssh/config
Traceback (most recent call last):
  File "/opt/boxen/homebrew/bin/dagobahd", line 7, in <module>
    from dagobah.daemon.app import daemon_entrypoint
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/app.py", line 1, in <module>
    from .daemon import app, login_manager
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 249, in <module>
    dagobah = init_dagobah()
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 126, in init_dagobah
    'multiple available in backend')
ValueError: could not infer dagobah ID, multiple available in backend```

**Comment by extrinsicmedia** [comment]
After trying an uninstall and reinstall of dagobah and removing the config file in order to try a complete fresh start this error occurs:
```Creating new config file in home directory
Traceback (most recent call last):
  File "/opt/boxen/homebrew/bin/dagobahd", line 7, in <module>
    from dagobah.daemon.app import daemon_entrypoint
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/app.py", line 1, in <module>
    from .daemon import app, login_manager
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 248, in <module>
    config = get_config_file()
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 70, in get_config_file
    new_config.write(return_standard_conf())
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/__init__.py", line 14, in return_standard_conf
    config_file = open(os.path.join(config_file_default_location, 'dagobahd.yml'))
IOError: [Errno 2] No such file or directory: '/private/var/root/dagobah/daemon/dagobahd.yml'```

**Comment by extrinsicmedia** [comment]
Followed the steps in Issue #159 but still getting this error:
```Creating new config file in home directory
Logging output to /opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/dagobah.log
INFO  [alembic.migration] Context impl SQLiteImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.
Defaulting missing config key Dagobahd.ssh_config to ~/.ssh/config
WARNI [root] Defaulting missing config key Dagobahd.ssh_config to ~/.ssh/config
Traceback (most recent call last):
  File "/opt/boxen/homebrew/bin/dagobahd", line 7, in <module>
    from dagobah.daemon.app import daemon_entrypoint
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/app.py", line 1, in <module>
    from .daemon import app, login_manager
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 249, in <module>
    dagobah = init_dagobah()
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/dagobah/daemon/daemon.py", line 126, in init_dagobah
    'multiple available in backend')
ValueError: could not infer dagobah ID, multiple available in backend```

Important to note that I'm not using virtualenv but am still having the same issue of dagobahd expecting the dagobah.yml (ignores ~/.dagobah.yml) file in a different location than previous installs.

**Comment by thieman** [comment]
Hey Miles, this message means that Dagobah's somehow managed to create multiple top-level Dagobah instances in your database, so it can't tell which one you should use. The fix is to go poke around in the `dagobah` table in the SQLite database and delete all the entries in that table other than the correct one which is linked to all your jobs

**Comment by extrinsicmedia** [comment]
@thieman, ended up deleting all the tables and starting over.  Luckily had saved some backups of my jobs.  Great to have that function.  Thanks for the tip on the SQLite database file.
