### ISSUE TITLE
Installation issue, missing gpost

### ISSUE THREAD

**Issue by macpit** [thieman/dagobah#176]
How i can resolve this issue?

`mm@srv:~/dagobah/dagobah$ dagobahd 
Traceback (most recent call last):
  File "/usr/local/bin/dagobahd", line 9, in <module>
    load_entry_point('dagobah==0.1.8', 'console_scripts', 'dagobahd')()
  File "/home/mpeter/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mpeter/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/mpeter/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/mpeter/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/dagobah-0.1.8-py2.7.egg/dagobah/__init__.py", line 4, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/dist-packages/dagobah-0.1.8-py2.7.egg/dagobah/core/__init__.py", line 2, in <module>
    from .components import JobState, Scheduler, EventHandler
  File "/usr/local/lib/python2.7/dist-packages/dagobah-0.1.8-py2.7.egg/dagobah/core/components.py", line 10, in <module>
    import post

ImportError: No module named gpost

mm@srv:~/dagobah/dagobah$ 
`

Best regards,

Marc

**Comment by thieman** [comment]
It seems like your'e using someone's fork, so you should ask the maintainer of the fork. We don't have a version 0.1.8 and I don't think my version has ever used the `gpost` library (I've never even heard of it before).
