### ISSUE TITLE
Fail to install dagobah

### ISSUE THREAD

**Issue by UriahLiu** [thieman/dagobah#201]
When I was trying to run
> pip install dagobah
It show a ERROR that

_lask-0.9.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\94723\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\94723\\AppData\\Local\\Temp\\pip-install-brzsdnen\\flask\\setup.py'"'"'; __file__='"'"'C:\\Users\\94723\\AppData\\Local\\Temp\\pip-install-brzsdnen\\flask\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\94723\AppData\Local\Temp\pip-install-brzsdnen\flask\pip-egg-info'
         cwd: C:\Users\94723\AppData\Local\Temp\pip-install-brzsdnen\flask\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\94723\AppData\Local\Temp\pip-install-brzsdnen\flask\setup.py", line 62
        print "Audit requires PyFlakes installed in your system."
                                                                ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Audit requires PyFlakes installed in your system.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output._

After I run install pyflakes,It's the same.
How can I fix it and run the whole program?

**Comment by josezy** [comment]
Try using python 2.7
